### ISSUE TITLE
Can i set the language to spanish?

### ISSUE THREAD

**Issue by diazh** [T00rk/bootstrap-material-datepicker#6]
I need to set the plugin to spanish, can i do this?

**Comment by T00rk** [comment]
Locales are managed by momentjs http://momentjs.com/.
To set spanish, you need to set lang to `es`.

Like this 
`$('#picker').bootstrapMaterialDatePicker({ format : 'DD/MM/YYYY HH:mm', lang : 'es', weekStart : 1 });`

**Comment by diazh** [comment]
Thanks!!

**Comment by hyz116** [comment]
How change the plugin UI colour?

**Comment by T00rk** [comment]
You can do it by editing css file
