### ISSUE TITLE
Error with currentDate

### ISSUE THREAD

**Issue by sbalant** [T00rk/bootstrap-material-datepicker#7]
When I set the currentDate, I get this error : TypeError: this.params.currentDate.format is not a function

$('#start_date').bootstrapMaterialDatePicker({ format : 'DD/MM/YYYY HH:mm', lang : 'fr', currentDate: '25/04/2015 15:23' })

In the code line 131, the element is set with the param currentDate instead of the currentDate created with moment :
this.$element.val(this.params.currentDate.format(this.params.format));
Should be :
this.$element.val(this.currentDate.format(this.params.format));

**Comment by T00rk** [comment]
Je l'ai corrigé mais je l'ai pas testé, je te fais confiance. Dis moi si ça marche.
Merci

**Comment by sbalant** [comment]
Ca fonctionne de mon cote :)

**Comment by T00rk** [comment]
Je clos l'issue. Merci pour ton aide
