### ISSUE TITLE
Set text on Cancel and Okay button

### ISSUE THREAD

**Issue by brendonjohn** [T00rk/bootstrap-material-datepicker#9]
Hello,

Thanks for your work on the date picker, it's really cool.

By default the text for the cancel button is "ANNULER" and the accept button is "OK". Presumably via the initial parameters, would you let a developer set their own text for these buttons when initialising the date-picker?

I can create a PR if need be.

Thank you

**Comment by T00rk** [comment]
It's done !
I've added two new parameters : 
**cancelText** : Text for the cancel button. By default it's Cancel
**okText** : Text for the okay button. By default it's Ok

**Comment by brendonjohn** [comment]
Stunning, thank you.

**Comment by nayanbhana** [comment]
Hi there! T00rk this is an awesome datepicker, thanks so much.
Is there any chance you can add this commit to the /peterzen/bootstrap-material-datepicker repository?

**Comment by T00rk** [comment]
Hi.
I don't undersand why. Peterzen's datepicker is a fork from mine.

**Comment by nayanbhana** [comment]
Peterzen's datepicker is used on our project and is 15 commits behind yours. There must be substantial differences because when I tried to use your repository it didn't work as intended. I could make the pull request if that is easier.

**Comment by T00rk** [comment]
Yes if you want

**Comment by T00rk** [comment]
I've changed the bower repository.
When Peterzen initialy did it he's set he's repository as the main repository.
Now you can use it with bower with `bower install bootstrap-material-datetimepicker`

**Comment by nayanbhana** [comment]
So you won't add the commit to peterzens repository? My project doesn't work with your repository, there must be differences as I said before. Ok, I will create a pull request on his repository. Thank you.

**Comment by T00rk** [comment]
Have you tried to change the name of the files.
As shown on the readme file, the js abd css files have been renamed to
bootstrap-material-datetimepicker.(js|css).
If that does not resolve your issue, let me know what the error is.

**Comment by nayanbhana** [comment]
It was my mistake T00rk. Thank you for your help. I was pulling master instead of gh-pages branch.

**Comment by T00rk** [comment]
Bonjour T00rk/bootstrap-material-datetimepicker,
AMERICA Romain vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/nLFvxO/q0p/?hg=hnoVL8pHxY pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=60ac5b60&email=reply@reply.github.com.&hg=hnoVL8pHxY
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by T00rk** [comment]
Bonjour T00rk/bootstrap-material-datetimepicker,


AMERICA Romain vous a laissé un message sur IQ Elite 


Cliquez ici a.iqelite.com/j/nLFvxO/q0p/?hg=68kWBovefX pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=60ac5b60&email=reply@reply.github.com.&hg=68kWBovefX
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------
